src/MagicVilla.Web/Controllers/AuthController.cs
using System.Security.Claims;
using System.Text;
using MagicVilla.Utility;
using MagicVilla.Web.Models;
using MagicVilla.Web.Models.Dto;
using MagicVilla.Web.Services.IService;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MagicVilla.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }
        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDto obj = new LoginRequestDto();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDto obj)
        {
            var response = await _authService.LoginAsync<ApiResponse>(obj);
            if (response != null && response.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(response.Result) ?? string.Empty);
                
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, model.User.Name));
                identity.AddClaim(new Claim(ClaimTypes.Role, model.User.Role));
                var principle = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principle);
                HttpContext.Session.SetString(StaticDetails.SessionToken, model.Token);
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("CustomError", response.ErrorMessage.FirstOrDefault());
            return View(obj);
        }

        [HttpGet]
        public async Task< IActionResult> Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegistrationRequestDto obj)
        {
           var result =  await _authService.RegistrationAsync<ApiResponse>(obj);
           if (result != null && result.IsSuccess)
           {
               return RedirectToAction("Login");
           }
           return View(obj);
        }

        public async Task<IActionResult> LogOut( )
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString(StaticDetails.SessionToken, "");
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }

        private  void CheckSession()
        {
            if (HttpContext.Session.TryGetValue(StaticDetails.SessionToken, out byte[] value))
            {
                // Session is set
                var token = Encoding.UTF8.GetString(value);
                // Do something with the token
            }
            else
            {
                // Session is not set
            }
        }
    }
}

src/MagicVilla.Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla.Web.Models;
using MagicVilla.Web.Models.Dto;
using MagicVilla.Web.Services.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using MagicVilla.Utility;

namespace MagicVilla.Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;
        private readonly ILogger<VillaController> _logger;

        public VillaController(IVillaService villaService, IMapper mapper, ILogger<VillaController> logger)
        {
            _villaService = villaService;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> IndexVilla()
        {
            var list = new List<VillaDto>();
            var response = await _villaService.GetVillaAsync<ApiResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null)
            {
                list = JsonConvert.DeserializeObject<List<VillaDto>>(response.Result.ToString() ?? string.Empty);
            }
            return View(list);
        }
        [Authorize(Roles = "admin")]
        public IActionResult CreateVilla()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVilla(VillaCreateDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.CreateAsync<ApiResponse>(model, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response is { IsSuccess: true })
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(int id)
        {
            var response = await _villaService.GetAsync<ApiResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response is not { IsSuccess: true }) return View();

            var model = JsonConvert.DeserializeObject<VillaDto>(response.Result.ToString() ?? string.Empty);

            return View(_mapper.Map<VillaUpdateDto>(model));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]

        public async Task<IActionResult> UpdateVilla(VillaUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.UpdateAsync<ApiResponse>(model, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response is { IsSuccess: true })
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(int id)
        {
            var response = await _villaService.GetAsync<ApiResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response is not { IsSuccess: true }) return NotFound();

            var model = JsonConvert.DeserializeObject<VillaDto>(response.Result.ToString() ?? string.Empty);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(VillaDto model)
        {
            var response = await _villaService.DeleteAsync<ApiResponse>(model.Id, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response is { IsSuccess: true })
            {
                return RedirectToAction(nameof(IndexVilla));
            }

            return View(model);
        }
    }
}

src/MagicVilla.Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla.Utility;
using MagicVilla.Web.Models;
using MagicVilla.Web.Models.Dto;
using MagicVilla.Web.Models.ViewModels;
using MagicVilla.Web.Services.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text;

namespace MagicVilla.Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;
        private readonly ILogger<VillaNumberController> _logger;


        public VillaNumberController(IVillaNumberService villaNumberService, IMapper mapper, IVillaService villaService, ILogger<VillaNumberController> logger)
        {
            _villaNumberService = villaNumberService;
            _mapper = mapper;
            _villaService = villaService;
            _logger = logger;
        }
        public async Task<IActionResult> IndexVillaNumber()
        {
            CheckSession();
            var list = new List<VillaNumberDto>();
            var response = await _villaNumberService.GetVillaAsync<ApiResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null)
            {
                list = JsonConvert.DeserializeObject<List<VillaNumberDto>>(response.Result.ToString() ?? string.Empty);
            }
            return View(list);
        }

        [Authorize(Roles = "admin")]

        public async Task<IActionResult> CreateVillaNumber()
        {
            var response = await _villaService.GetVillaAsync<ApiResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var model = new VillaNumberCreateVm();
            if (response is { IsSuccess: true })
            {
                //we should throw an exception if serialization property doesn't match 
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "admin")]

        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVm model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.CreateAsync<ApiResponse>(model.VillaNumber, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response is { IsSuccess: true })
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]

        public async Task<IActionResult> UpdateVillaNumber(int id)
        {
            var villaNumberUpdateVm = new VillaNumberUpdateVm();
            var response = await _villaNumberService.GetAsync<ApiResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response is not { IsSuccess: true }) return View();

            var model = JsonConvert.DeserializeObject<VillaNumberDto>(response.Result.ToString() ?? string.Empty);

            villaNumberUpdateVm.VillaNumber = _mapper.Map<VillaNumberUpdateDto>(model);

            response = await _villaService.GetVillaAsync<ApiResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response is { IsSuccess: true })
            {
                //we should throw an exception if serialization property doesn't match 
                villaNumberUpdateVm.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            return View(villaNumberUpdateVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]

        public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVm model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.UpdateAsync<ApiResponse>(model.VillaNumber, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response is { IsSuccess: true })
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]

        public async Task<IActionResult> DeleteVillaNumber(int id)
        {
            var villaNumberDeleteVm = new VillaNumberDeleteVm();

            var response = await _villaNumberService.GetAsync<ApiResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response is not { IsSuccess: true }) return NotFound();


            villaNumberDeleteVm.VillaNumber = JsonConvert.DeserializeObject<VillaNumberDto>(response.Result.ToString() ?? string.Empty);

            response = await _villaService.GetVillaAsync<ApiResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response is { IsSuccess: true })
            {
                //we should throw an exception if serialization property doesn't match 
                villaNumberDeleteVm.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            return View(villaNumberDeleteVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]

        public async Task<IActionResult> DeleteVillaNumber(VillaNumberDeleteVm model)
        {
            var response = await _villaNumberService.DeleteAsync<ApiResponse>(model.VillaNumber.VillaNo, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response is { IsSuccess: true })
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }

            return View(model);
        }

        private void CheckSession()
        {
            if (HttpContext.Session.TryGetValue(StaticDetails.SessionToken, out byte[] value))
            {
                // Session is set
                var token = Encoding.UTF8.GetString(value);
                _logger.LogInformation("Session is set: "+ token);
            }
            else
            {
                // Session is not set
            }
        }
    }
}

src/MagicVilla.Web/Views/Shared/_Layout.cshtml
@using MagicVilla.Utility
@inject IHttpContextAccessor httpContext

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagicVilla.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Number</a>
                        </li>
                        @if (httpContext.HttpContext.Session.GetString(StaticDetails.SessionToken) != null &&
                        httpContext.HttpContext.Session.GetString(StaticDetails.SessionToken).ToString().Length > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="LogOut">LogOut</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MagicVilla.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>